spring.application.name=retotiendaartesanal-backend
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3307/retotiendaartesanal
spring.datasource.username=reto_user
spring.datasource.password=reto_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=57Se9EiN618IctHQdHvDDajpkUbUdpx7oMPqErxLt1reR6BifgTrJFqe0zri/WK/Ogzv0rv+CxThIfZrfgGYlw==
jwt.expiration=86400000