spring.application.name=reto-ahorro-backend
server.port=8080
server.servlet.context-path=/api

# --- Base de datos MySQL ---
spring.datasource.url=jdbc:mysql://localhost:3306/reto_ahorro?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
spring.datasource.username=reto_user
spring.datasource.password=Root#2026mysql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- JWT ---
# Secreto generado para desarrollo. Cambialo en produccion (variable de entorno).
jwt.secret=qJJ59an16wsHbj4+nEE1sCWCDd3CqA+b0RsQOlZPcLN+6LHPlR3dkIQAxd/RiytOO+enphNnngKB+0yjECTt1A==
jwt.expiration-ms=86400000

# --- CORS (frontend Vite) ---
app.cors.allowed-origin=http://localhost:5173
