spring.application.name=capsula-backend

spring.datasource.url=jdbc:mysql://localhost:3306/capsula_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Root#2026mysql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

jwt.secret=siZf4B709mAmY1T13Rtqac4JX8apuPH+WDyY1utrh/M=
jwt.expiration-ms=86400000

# limite de tamano de request para poder subir fotos como base64
spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=8MB
server.tomcat.max-swallow-size=10MB
server.tomcat.max-http-form-post-size=10MB
