services:
  mysql:
    image: mysql:8.0
    container_name: retoTiendaArtesanal_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: retotiendaartesanal
      MYSQL_USER: reto_user
      MYSQL_PASSWORD: reto_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit:latest
    container_name: retoTiendaArtesanal_mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  mysql_data:
